### ISSUE TITLE
Start week from Monday

### ISSUE THREAD

**Issue by elehcim** [danielpinto8zz6/budgie-calendar-applet#13]
Hello,
in the current view each week of the calendar starts with a Sunday.
![screenshot from 2018-02-07 10-25-56](https://user-images.githubusercontent.com/1649109/35908596-77f59da4-0bf1-11e8-8682-f0219911c249.png)
is it possible to start the week from Mondays (as in `ncal -M`) ?

**Comment by danielpinto8zz6** [comment]
I'm not sure, I cant take a look

**Comment by zacharyPuthoff** [comment]
I'll add my vote to the request for this feature.

**Comment by Tonicrespit** [comment]
The calendar uses the system's format. You can go to Settings > Region & Language and set a format that uses Monday as the first day of the week (for example "United Kingdom"). After restarting the computer, your calendar will have the weeks starting on Monday.

Note that changing this will also change the default calendar desktop app so that it also starts its weeks on Monday.

**Comment by elehcim** [comment]
@Tonicrespit It works, thank you.
