### ISSUE TITLE
Doesn't highlight today's date

### ISSUE THREAD

**Issue by razcakappa** [danielpinto8zz6/budgie-calendar-applet#25]
I've installed this applet with Solus4 Budgie. While appreciating the effort and as this is a very useful applet, I'd like to point out that when I open the calendar pop-over, it doesn't highlight today's specific date. However clicking on a day makes it highlight.

![Screenshot from 2020-07-16 12-30-35](https://user-images.githubusercontent.com/4122440/87638013-b410a900-c760-11ea-9f96-512247017633.png)
![Screenshot from 2020-07-16 12-30-53](https://user-images.githubusercontent.com/4122440/87638022-b96df380-c760-11ea-9f9a-17706b55fd04.png)

I'm not sure whether this is a feature request or bug. Just probing here to see any work-around for this problem.

**Comment by DasJott** [comment]
Yeah, highlighting the current day would be nice!

**Comment by zilexa** [comment]
This is not an enhancement. It's a bug.

I'm not a dev but this issue gives me a short circuited brain couple of times a day. Perhaps I'll figure it out, then also figure out how github works, what and how to do a pull. Thats how crazy it makes me, even though it's probably a minor thing.

**Comment by danielpinto8zz6** [comment]
It's not a bug, it's the normal behavior of the gtk calendar, so adding this feature will be an enhancement

**Comment by fossfreedom** [comment]
Daniel - you appear to have already solved this https://github.com/danielpinto8zz6/budgie-calendar-applet/commit/97e4510129967b1cdbb0bd16836a782bbdff4b4f#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

The OP is probably reporting this because solus is using your 5.2 official package - but that commit was released after the last official release.

I've now patched Ubuntu Budgie's version with the extra commit now.

**Comment by danielpinto8zz6** [comment]
Hi @fossfreedom, so I added that feature almost 3 years ago, I didn't remember ahah, thank you for letting me know
